platform:
  network:
    name: imanai-tap
  infra:
    observability: ./deployment/docker-compose/observability.yml
  boundedContexts:
    dir: "../bounded-contexts"
    services:
      - name: mds-historical
        repo: "https://github.com/komelgman/imanai-tap.mds-historical.git"
